/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package pl.futurecollars.invoicing;

import java.io.File;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import pl.futurecollars.invoicing.db.Database;
import pl.futurecollars.invoicing.db.memory.InMemoryDatabase;
import pl.futurecollars.invoicing.model.Company;
import pl.futurecollars.invoicing.model.Invoice;
import pl.futurecollars.invoicing.model.InvoiceEntry;
import pl.futurecollars.invoicing.model.Vat;
import pl.futurecollars.invoicing.service.InvoiceService;

public class App {

  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    Database db = new InMemoryDatabase();
    InvoiceService service = new InvoiceService(db);
    Company buyer = new Company("123-345-467", "ul. Nijaka 1/2 Nigdzie", "MojaFima");
    Company seller = new Company("456-333-123", "ul. Nijaka 4/5 Nigdzie", "TwojaFima");
    List<InvoiceEntry> products = List.of(new InvoiceEntry("Wypozyczenie sprzetu", BigDecimal.valueOf(100), BigDecimal.TEN, Vat.VAT_8));
    Invoice invoice = new Invoice(LocalDate.now(), buyer, seller, products);
    int id = service.save(invoice);

    service.delete(id);
    System.out.println(invoice.toString());






  // wujatek
//zapis do pliku - invoice.json -open in -explorer-
  ///window (c) -invoice.json


    System.out.println(new App().getGreeting());
  }
}
