name: CI
on:
  push:
    branches: [master]
    pull_request:
      branches: [master]
      workflow_dispatch:

        jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2
          - name: Set up JDK 14
            uses: actions/setup-java@v1
            with:
              java-version: '14'
              distribution: 'temurin'
          - name: Build with gradle
            uses: ./ gradlew build
          - name: Build with Gradle
            uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
            with:
              arguments: build